services:
  database:
    profiles: [prod, dev, server]
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    profiles: [prod, dev, server]
    image: redis:7
    ports:
      - ${REDIS_PORT:-6379}:6379
    volumes:
      - ./data/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  nuxt:
    profiles: [prod]
    build:
      context: /apps/nuxt
      dockerfile: Dockerfile.prod
    env_file: /apps/nuxt/.env
    volumes:
      - /apps/nuxt:/app
    ports:
      - ${NUXT_PORT:-3000}:3000

  nuxt-dev:
    profiles: [dev]
    build:
      context: /apps/nuxt
      dockerfile: Dockerfile.dev
    env_file: /apps/nuxt/.env
    volumes:
      - /apps/nuxt:/app
    ports:
      - ${NUXT_PORT:-3000}:3000

  medusa:
    profiles: [prod]
    build:
      context: /apps/medusa
      dockerfile: Dockerfile.prod
    env_file: /apps/medusa/.env
    volumes:
      - /apps/medusa:/app
    ports:
      - ${MEDUSA_PORT:-9000}:9000

  medusa-dev:
    profiles: [dev]
    build:
      context: /apps/medusa
      dockerfile: Dockerfile.dev
    env_file: /apps/medusa/.env
    volumes:
      - /apps/medusa:/app
    ports:
      - ${MEDUSA_PORT:-9000}:9000
