FROM node:lts-alpine AS base

RUN mkdir -p /usr/src/nuxt
WORKDIR /usr/src/nuxt

RUN npm install -g pnpm

# RUN mkdir -p .output/server
# RUN touch .output/server/index.mjs

ENTRYPOINT ["node", ".output/server/index.mjs"]